#!/bin/sh

# 固定IP
uci set network.lan.ipaddr='192.168.11.1'
uci set network.lan.netmask='255.255.255.0'

# 自动LAN桥接（不写死网口！避免翻车）
uci set network.lan.type='bridge'

uci -q delete network.lan.device
for i in $(ls /sys/class/net | grep -E 'eth|en|lan'); do
    uci add_list network.lan.device="$i"
done

# 关闭IPv6
uci delete network.wan6 2>/dev/null
uci set dhcp.lan.dhcpv6='disabled'
uci set dhcp.lan.ra='disabled'
uci set dhcp.lan.ndp='disabled'

# DNS防污染
uci set dhcp.@dnsmasq[0].noresolv='1'
uci -q delete dhcp.@dnsmasq[0].server
uci add_list dhcp.@dnsmasq[0].server='1.1.1.1'
uci add_list dhcp.@dnsmasq[0].server='8.8.8.8'

# 应用
uci commit network
uci commit dhcp

/etc/init.d/network restart
/etc/init.d/dnsmasq restart

# 删除自身（一次性）
rm -f /etc/uci-defaults/99-proxy-init

exit 0
