name: ImmortalWrt 24.10.6 Stable

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # =========================
      # Build firmware (stable)
      # =========================
      - name: Build firmware
        run: |
          set -e

          docker pull ghcr.io/immortalwrt/imagebuilder:x86-64-24.10.6

          docker run --rm \
            --user root \
            -v $PWD:/builder \
            -w /builder \
            ghcr.io/immortalwrt/imagebuilder:x86-64-24.10.6 \
            /bin/bash /builder/shell/build.sh

      # =========================
      # Upload artifact
      # =========================
      - name: Upload firmware
        uses: softprops/action-gh-release@v2
        with:
          tag_name: fw-24.10.6
          files: bin/targets/x86/64/*squashfs-combined-efi.img.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
