name: ImmortalWrt 24.10.6 Stable

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Build firmware
        run: |
          docker run --rm \
            -v $PWD:/builder \
            -w /builder \
            ghcr.io/immortalwrt/imagebuilder:x86-64-24.10.6 \
            /bin/bash shell/build.sh

      - name: Upload
        uses: softprops/action-gh-release@v2
        with:
          tag_name: fw-24.10.6
          files: bin/targets/x86/64/*img.gz
